name: Lint

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Lint with Ruff
              run: |
                  pip install ruff
                  ruff check --output-format=github .
